### ISSUE TITLE
Dialog box corner is not animated

### ISSUE THREAD

**Issue by SergeyMC9730** [Reinmmar/DeltaruneTextboxes#1]
![image](https://github.com/user-attachments/assets/0e95bac6-4564-4659-82fd-c63f98ab01cc)
In the original game all non-overworld dialogs have box corners animated (1 pixel surrounded by 9 empty pixels was changing their color each 250 milliseconds)
Would be nice to have something like this in your mod

**Comment by Reinmmar** [comment]
I did not know that lol

**Comment by Reinmmar** [comment]
Will do that in a future update, I am gonna submit 1.1.0 now and maybe after that I'll look into it

**Comment by Reinmmar** [comment]
Implemented it now :D
