### ISSUE TITLE
Request for the border to be changed by the undertale one

### ISSUE THREAD

**Issue by freakingdan** [Reinmmar/DeltaruneTextboxes#3]
**As the title states**... i want the border to be changed to the _undertale_ one or _any border_ i like in the options.

**Comment by Reinmmar** [comment]
I get where you're coming from but the mod's name is literally Deltarune Textboxes lmao, I can add a setting that disables the animation on the background and then you can change the texture of the first frame using texture loader if you want. Idk maybe I will add an option for undertale background

**Comment by freakingdan** [comment]
i know... but maybe you will add the option to look like real undertale...
_i have the both underdash mod and the deltarune texboxes_
what i mean by that is i want the GD interface to look like the real undertale with complete ud bg music and ud textboxes ;)

**Comment by Reinmmar** [comment]
Yeah sure, should be easy to implement!
